### ISSUE TITLE
Legacy webhook library

### ISSUE THREAD

**Issue by 0arm** [theandychung/discord-weibo-bot#3]
I was looking through the dependants of [kyb3r/dhooks](https://github.com/kyb3r/dhooks) and found yours, I was looking through the source code and found that you are using an outdated version of the library. The current version on PyPI has a different API so it will break your code when you deploy to heroku. Check the [README.md](https://github.com/kyb3r/dhooks) and [docs](https://dhooks.readthedocs.io/) to see what's new. 👍

**Comment by theandychung** [comment]
Thank you for reminding me, but I think I'm using the most current version (v1.0.8). I haven't notice anything different yet, could you tell me where you see the problem?
