### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Roy47Zhang** [theandychung/discord-weibo-bot#5]
I followed her with Readme.md, configured and created the app, but no microblog was sent to Discord. Is there any heroku log available for querying so I can troubleshoot it?

**Comment by theandychung** [comment]
I use this command
`heroku logs --app discord-weibo-bot -t -n 15`
but you need to install something from heroku.

**Comment by Roy47Zhang** [comment]
`(Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))`
Ummm looks like proxy has some problem?

**Comment by theandychung** [comment]
I'm still using it lol

**Comment by theandychung** [comment]
There is a possibility that all the ip on page one of https://www.sslproxies.org/ has been used, and none of them work. In that case you won't be able to use any IP because I didn't tell it to flip the page  : P

Let me know if this is the issue.

**Comment by Roy47Zhang** [comment]
https://github.com/theandychung/discord-weibo-bot/issues/4
same problem but after add heroku python buildpack and git push heroku once 
it's working now thank you
